import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  header: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
  },
  headerButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
  },
  headerTitle: { flex: 1, textAlign: 'center' },
  headerSpacer: { width: 40 },
  pressed: { opacity: 0.72 },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    gap: spacing.md,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  errorCard: {
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.xl,
    borderRadius: rounded.xxxl,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.canvas,
  },
  errorIcon: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxs,
    borderRadius: rounded.full,
    backgroundColor: colors['surface-yellow'],
  },
  title: { textAlign: 'center' },
  description: { maxWidth: 300, color: colors.slate, textAlign: 'center' },
  inboxButton: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.xl,
    borderRadius: rounded.full,
    backgroundColor: colors.primary,
  },
  inboxButtonText: { color: colors['on-primary'] },
  privacyNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    padding: spacing.md,
    borderRadius: rounded.lg,
    backgroundColor: colors.surface,
  },
  privacyText: { flex: 1, color: colors.steel },
});
