import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  header: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
  },
  headerButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
  },
  headerTitle: { flex: 1, textAlign: 'center' },
  pressed: { opacity: 0.7 },
  content: { flexGrow: 1, padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xl },
  titleGroup: { gap: spacing.xxs, marginBottom: spacing.xs },
  title: { fontSize: 22, lineHeight: 28 },
  subtitle: { color: colors.slate },
  searchField: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.md,
    borderWidth: 1,
    borderColor: colors.hairline,
    backgroundColor: colors.surface,
  },
  searchInput: { flex: 1, minHeight: 46, paddingVertical: spacing.xs, color: colors.ink, fontSize: 15 },
  clearButton: { width: 28, height: 36, alignItems: 'center', justifyContent: 'center' },
  notice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    padding: spacing.sm,
    borderRadius: rounded.md,
    backgroundColor: colors['surface-yellow'],
  },
  noticeText: { flex: 1, color: colors.slate },
  resultHeading: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
    paddingHorizontal: spacing.xxs,
  },
  resultLabel: { color: colors.steel, letterSpacing: 0.4 },
  keyword: { flex: 1, color: colors.slate, textAlign: 'right' },
  emptyCard: {
    minHeight: 188,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.lg,
    borderRadius: rounded.xl,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.canvas,
  },
  emptyIcon: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxs,
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
  },
  emptyTitle: { textAlign: 'center' },
  emptyDescription: { maxWidth: 260, color: colors.steel, textAlign: 'center' },
  requestsLink: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.xl,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.surface,
  },
  requestsCopy: { flex: 1, gap: spacing.xxs },
  requestsHint: { color: colors.slate },
});
