import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  header: {
    minHeight: 60,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brand: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  brandMark: {
    width: 30,
    height: 30,
    borderRadius: rounded.md,
    backgroundColor: colors['brand-yellow'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLetter: { color: colors.ink },
  brandName: { color: colors.ink, letterSpacing: 1.2 },
  avatarButton: {
    width: 40,
    height: 40,
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.hairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: colors.slate },
  pressed: { opacity: 0.7 },
  content: { padding: spacing.lg, gap: spacing.lg, flexGrow: 1 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  titleCopy: { flex: 1, gap: spacing.xxs },
  title: { fontSize: 24, lineHeight: 30 },
  subtitle: { color: colors.slate },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    backgroundColor: colors.surface,
    borderRadius: rounded.full,
    paddingVertical: spacing.xxs,
    paddingHorizontal: spacing.sm,
  },
  statusDot: { width: 7, height: 7, borderRadius: rounded.full, backgroundColor: colors.stone },
  statusText: { color: colors.steel },
  createButton: {
    minHeight: 48,
    borderRadius: rounded.full,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  createButtonPressed: { backgroundColor: colors.charcoal },
  createButtonText: { color: colors['on-primary'] },
  friendsLink: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.canvas,
  },
  friendsLinkPressed: { opacity: 0.72 },
  friendsLinkIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
  },
  friendsLinkCopy: { flex: 1, gap: 2 },
  friendsLinkHint: { color: colors.steel },
  connectionNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors['surface-yellow'],
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
  },
  connectionText: { flex: 1, color: colors.slate },
  emptyCard: {
    minHeight: 280,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.xl,
    backgroundColor: colors.canvas,
    borderRadius: rounded.xl,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  emptyTitle: { textAlign: 'center' },
  emptyDescription: { color: colors.steel, textAlign: 'center', maxWidth: 280 },
});
