import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  header: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
  },
  headerButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
  },
  headerTitle: { flex: 1, textAlign: 'center' },
  headerSpacer: { width: 40 },
  pressed: { opacity: 0.72 },
  content: { flexGrow: 1, gap: spacing.lg, padding: spacing.lg, paddingBottom: spacing.xl },
  profileSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  avatar: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
    backgroundColor: colors['yellow-light'],
  },
  avatarText: { color: colors['yellow-dark'] },
  profileCopy: { flex: 1, gap: spacing.xxs },
  secondaryText: { color: colors.slate },
  section: { gap: spacing.md },
  field: { gap: spacing.xs },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors['hairline-strong'],
    borderRadius: rounded.md,
    paddingHorizontal: spacing.md,
    color: colors.ink,
    backgroundColor: colors.canvas,
    fontSize: 15,
  },
  readOnlyInput: {
    justifyContent: 'center',
    borderColor: colors.hairline,
    backgroundColor: colors.surface,
  },
  readOnlyText: { color: colors.steel },
  helper: { color: colors.steel },
  successNotice: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.md,
    backgroundColor: colors['surface-yellow'],
  },
  successText: { flex: 1, color: colors['moss-dark'] },
  settingsLink: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.surface,
  },
  settingsLinkText: { flex: 1 },
  logoutButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: rounded.full,
    borderWidth: 1,
    borderColor: colors['brand-red-dark'],
    backgroundColor: colors['brand-red'],
  },
  logoutText: { color: colors['coral-dark'] },
});
