import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  keyboardArea: { flex: 1 },
  header: {
    minHeight: 56,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { flex: 1, textAlign: 'center' },
  headerSpacer: { width: 40 },
  pressed: { opacity: 0.72 },
  content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xxl },
  titleGroup: { gap: spacing.xxs },
  title: { fontSize: 24, lineHeight: 30 },
  subtitle: { color: colors.slate },
  availabilityNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors.hairline,
  },
  noticeText: { flex: 1, color: colors.slate },
  fieldGroup: { gap: spacing.sm },
  segmentedControl: {
    flexDirection: 'row',
    gap: spacing.xxs,
    padding: spacing.xxs,
    backgroundColor: colors.surface,
    borderRadius: rounded.lg,
  },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: rounded.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  segmentButtonSelected: { backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.hairline },
  segmentText: { color: colors.slate },
  segmentTextSelected: { color: colors.ink },
  selectedRecipient: {
    minHeight: 60,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors['hairline-strong'],
    borderRadius: rounded.lg,
  },
  recipientAvatar: {
    width: 36,
    height: 36,
    borderRadius: rounded.full,
    backgroundColor: colors['yellow-light'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipientInitial: { color: colors['yellow-dark'] },
  recipientCopy: { flex: 1, gap: 2 },
  secondaryText: { color: colors.steel },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors['hairline-strong'],
    borderRadius: rounded.md,
    paddingHorizontal: spacing.md,
    color: colors.ink,
    backgroundColor: colors.canvas,
    fontSize: 16,
  },
  multilineInput: { minHeight: 112, paddingTop: spacing.md },
  helper: { color: colors.steel },
  deliveryList: { gap: spacing.xs },
  deliveryOption: {
    minHeight: 72,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: colors.hairline,
    borderRadius: rounded.lg,
    backgroundColor: colors.canvas,
  },
  deliveryOptionSelected: { borderColor: colors.primary, backgroundColor: colors.surface },
  deliveryCopy: { flex: 1, gap: spacing.xxs },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: rounded.full,
    borderWidth: 1.5,
    borderColor: colors['hairline-strong'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: { borderColor: colors.primary },
  radioInner: { width: 10, height: 10, borderRadius: rounded.full, backgroundColor: colors.primary },
  scheduleCard: {
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: rounded.lg,
    backgroundColor: colors.surface,
  },
  scheduleFields: { flexDirection: 'row', gap: spacing.sm },
  scheduleField: { flex: 1, gap: spacing.xxs },
  fieldHint: { color: colors.slate },
  scheduleInput: {
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors['hairline-strong'],
    borderRadius: rounded.md,
    paddingHorizontal: spacing.sm,
    color: colors.ink,
    backgroundColor: colors.canvas,
  },
  infoPanel: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: rounded.md,
  },
  infoPanelText: { flex: 1, color: colors.slate },
  submitArea: { gap: spacing.sm, marginTop: spacing.xs },
  cancelButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: rounded.full,
    borderWidth: 1,
    borderColor: colors.hairline,
  },
  cancelText: { color: colors.ink },
});
