import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.canvas },
  header: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors['hairline-soft'],
  },
  headerCopy: { flex: 1 },
  addButton: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xxs,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.full,
    backgroundColor: colors.primary,
  },
  addButtonText: { color: colors['on-primary'] },
  pressed: { opacity: 0.72 },
  content: { flexGrow: 1, padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xl },
  titleGroup: { gap: spacing.xxs },
  title: { fontSize: 24, lineHeight: 30 },
  subtitle: { color: colors.slate },
  tabRail: {
    flexDirection: 'row',
    gap: spacing.xxs,
    padding: spacing.xxs,
    borderRadius: rounded.lg,
    backgroundColor: colors.surface,
  },
  tab: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxs,
    borderRadius: rounded.md,
  },
  tabSelected: { backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.hairline },
  tabText: { color: colors.slate, textAlign: 'center', fontSize: 11 },
  tabTextSelected: { color: colors.ink },
  notice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xs,
    padding: spacing.md,
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors.hairline,
    backgroundColor: colors.surface,
  },
  noticeText: { flex: 1, color: colors.slate },
  sectionHeading: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
    paddingHorizontal: spacing.xxs,
  },
  sectionLabel: { color: colors.steel, letterSpacing: 0.4 },
  sectionHint: { color: colors.steel },
  emptyCard: {
    minHeight: 204,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.lg,
    borderRadius: rounded.xl,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.canvas,
  },
  emptyIcon: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xxs,
    borderRadius: rounded.full,
    backgroundColor: colors.surface,
  },
  emptyTitle: { textAlign: 'center' },
  emptyDescription: { maxWidth: 280, color: colors.steel, textAlign: 'center' },
  searchLink: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: rounded.lg,
    borderWidth: 1,
    borderColor: colors['hairline-soft'],
    backgroundColor: colors.surface,
  },
  searchLinkText: { flex: 1 },
});
