import { StyleSheet } from 'react-native';
import { colors, rounded, spacing } from '@nexa/design-tokens';

export const styles = StyleSheet.create({
  scrim: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: colors['overlay-scrim'],
  },
  dialog: {
    width: '100%',
    maxWidth: 420,
    gap: spacing.sm,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors['hairline-strong'],
    borderRadius: rounded.xl,
    backgroundColor: colors.canvas,
    shadowColor: colors.black,
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  title: { color: colors.ink },
  message: { color: colors.slate },
  actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs },
  cancelButton: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    borderWidth: 1,
    borderColor: colors.hairline,
    borderRadius: rounded.full,
  },
  cancelText: { color: colors.ink, textAlign: 'center' },
  confirmButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: rounded.full,
    backgroundColor: colors.primary,
  },
  confirmDestructive: { backgroundColor: colors.danger },
  confirmText: { color: colors['on-primary'], textAlign: 'center' },
  busy: { opacity: 0.88 },
  pressed: { opacity: 0.72 },
});
